    # netlify.toml (standalone)

    [build]
      # NO base directory specified. All paths below are relative to the root.

      # Build command: cd into the app directory, install, and build
      command = "cd app && npm install && npm run build"

      # Publish directory relative to the repository root
      publish = "app/build/"

      # Functions directory relative to the repository root
      functions = "netlify/functions/"

    # Redirect rule for the API proxy function
    [[redirects]]
      from = "/api/*"
      to = "/.netlify/functions/:splat"
      status = 200

    # Optional redirect...
    # [[redirects]]
    #  from = "/"
    #  to = "/index.html"
    #  status = 200