# netlify.toml (standalone)

[build]
  # Base directory relative to the new repository root
  base = "app/"
  
  # Build command (runs inside base directory)
  command = "npm install && npm run build"
  
  # Publish directory relative to the new repository root
  publish = "app/build/"
  
  # Functions directory relative to the new repository root
  functions = "netlify/functions/"

# Redirect rule for the API proxy function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional: Redirect rule if you want the root of your Netlify site
# to directly show the VM manager app.
# [[redirects]]
#  from = "/"
#  to = "/index.html"  # This might need to point to /app/index.html or similar if not using a root redirect
#  status = 200 